apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
images:
- name: hello-gitops
  newName: vfiftyfive/hello-gitops
  newTag: 97aa45a45c9c19755d66a47c0cc80e2064ac100a
