apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- workspace.yaml
- namespace.yaml
images:
- name: hello-gitops
  newName: vfiftyfive/hello-gitops
  newTag: 87519c9db083ece25be5603298f3a4083885122b
