apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- workspace.yaml
- namespace.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: vfiftyfive/hello-gitops
  newTag: d73af99a18e862273ec9049e2a87fbfc61653463
configMapGenerator:
- literals:
  - username=admin
  - url="https://172.31.186.4"
  name: tf-inputs
configurations:
- ./kustomizeconfig/workspace.yaml
