apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- networkpolicy.yaml
images:
- name: hello-gitops
  newName: vfiftyfive/hello-gitops
  newTag: 536fbfb9792a0c08a9650845f8f82d3f24bf0eef
